"""
PDF Chunker — Chia PDF sách dài thành nhiều chunk nhỏ
Dùng PyMuPDF (fitz) để tách page, không cần re-render
"""

import logging
import shutil
from pathlib import Path
from typing import Generator

import fitz  # PyMuPDF

from config import (
    CHUNK_SIZE_PAGES,
    LARGE_BOOK_PAGES,
    LARGE_BOOK_SIZE_MB,
    TEMP_DIR,
)

logger = logging.getLogger(__name__)


def is_large_book(pdf_path: Path) -> bool:
    """
    Kiểm tra xem file có phải sách dài không.
    Dựa trên: kích thước file HOẶC số trang.
    """
    size_mb = pdf_path.stat().st_size / 1e6

    if size_mb >= LARGE_BOOK_SIZE_MB:
        logger.info(
            f"[{pdf_path.name}] Phát hiện sách lớn: "
            f"{size_mb:.1f} MB >= ngưỡng {LARGE_BOOK_SIZE_MB} MB"
        )
        return True

    # Đếm trang nhanh (không load toàn bộ)
    try:
        with fitz.open(str(pdf_path)) as doc:
            n_pages = len(doc)
        if n_pages >= LARGE_BOOK_PAGES:
            logger.info(
                f"[{pdf_path.name}] Phát hiện sách dài: "
                f"{n_pages} trang >= ngưỡng {LARGE_BOOK_PAGES} trang"
            )
            return True
    except Exception as e:
        logger.warning(f"Không đọc được số trang của {pdf_path.name}: {e}")

    return False


def get_page_count(pdf_path: Path) -> int:
    """Đếm số trang trong PDF."""
    with fitz.open(str(pdf_path)) as doc:
        return len(doc)


def split_pdf_into_chunks(
    pdf_path: Path,
    chunk_size: int = CHUNK_SIZE_PAGES,
) -> list[Path]:
    """
    Chia PDF thành nhiều file chunk nhỏ, mỗi chunk `chunk_size` trang.

    Returns:
        Danh sách đường dẫn đến các file chunk (trong TEMP_DIR).
    """
    stem = pdf_path.stem
    chunk_dir = TEMP_DIR / stem
    chunk_dir.mkdir(parents=True, exist_ok=True)

    chunk_paths: list[Path] = []

    with fitz.open(str(pdf_path)) as src_doc:
        total_pages = len(src_doc)
        total_chunks = (total_pages + chunk_size - 1) // chunk_size

        logger.info(
            f"[{pdf_path.name}] Chia thành {total_chunks} chunk "
            f"({chunk_size} trang/chunk, tổng {total_pages} trang)"
        )

        for chunk_idx in range(total_chunks):
            start = chunk_idx * chunk_size
            end   = min(start + chunk_size, total_pages)

            chunk_path = chunk_dir / f"{stem}_chunk_{chunk_idx+1:03d}_p{start+1}-{end}.pdf"

            # Tạo PDF mới chứa các trang trong range [start, end)
            chunk_doc = fitz.open()
            chunk_doc.insert_pdf(src_doc, from_page=start, to_page=end - 1)
            chunk_doc.save(str(chunk_path))
            chunk_doc.close()

            chunk_paths.append(chunk_path)
            logger.debug(
                f"  Chunk {chunk_idx+1}/{total_chunks}: "
                f"trang {start+1}–{end} → {chunk_path.name}"
            )

    return chunk_paths


def cleanup_chunks(pdf_path: Path) -> None:
    """Xóa thư mục chunk tạm sau khi xử lý xong."""
    chunk_dir = TEMP_DIR / pdf_path.stem
    if chunk_dir.exists():
        shutil.rmtree(chunk_dir)
        logger.debug(f"Đã xóa thư mục chunk tạm: {chunk_dir}")


def merge_markdown_chunks(
    chunk_md_paths: list[Path],
    output_path: Path,
    pdf_name: str,
) -> None:
    """
    Ghép các file markdown chunk lại thành 1 file markdown hoàn chỉnh.
    Thêm separator giữa các chunk để dễ phân biệt.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as out_f:
        # Header metadata
        out_f.write(f"<!-- Source: {pdf_name} -->\n")
        out_f.write(f"<!-- Generated by MinerU PDF2Markdown Pipeline -->\n\n")

        for i, chunk_path in enumerate(sorted(chunk_md_paths)):
            if not chunk_path.exists():
                logger.warning(f"Chunk markdown không tồn tại: {chunk_path}")
                continue

            chunk_content = chunk_path.read_text(encoding="utf-8", errors="replace")

            # Separator giữa các chunk (tùy chọn, có thể bỏ)
            if i > 0:
                out_f.write("\n\n")  # Chỉ newline, không separator rõ ràng

            out_f.write(chunk_content.strip())
            out_f.write("\n")

    logger.info(
        f"Đã ghép {len(chunk_md_paths)} chunk → {output_path.name} "
        f"({output_path.stat().st_size / 1e3:.1f} KB)"
    )
